# Generated by Django 2.0.4 on 2018-04-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gems',
            field=models.IntegerField(verbose_name='Gemas'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.BooleanField(verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lives',
            field=models.IntegerField(verbose_name='Vidas'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='player',
            name='power',
            field=models.IntegerField(verbose_name='Poder'),
        ),
    ]
