# Generated by Django 2.0.4 on 2018-04-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fight_game', '0003_combat_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combat',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='combat_winner', to='fight_game.Fighter', verbose_name='Ganador'),
            preserve_default=False,
        ),
    ]
