# Generated by Django 2.0.4 on 2018-04-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fight_game', '0004_auto_20180423_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combat',
            name='fighter1',
        ),
        migrations.RemoveField(
            model_name='combat',
            name='fighter2',
        ),
        migrations.AddField(
            model_name='combat',
            name='loser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='combat_loser', to='fight_game.Fighter', verbose_name='Perdedor'),
            preserve_default=False,
        ),
    ]
